version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
configuration:
  - Debug
  - Release
clone_folder: C:\openvswitch_compile
init:
- ps: $env:PATH ="C:\Python37;"+$env:PATH
- ps: New-Item -Type HardLink -Path "C:\Python37\python3.exe" -Value "C:\Python37\python.exe"
- ps: >-
    mkdir C:\pthreads-win32

    mkdir C:\ovs-build-downloads\ssl

    $source = "https://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip"

    $destination = "C:\pthreads-win32\pthreads-win32.zip"

    Invoke-WebRequest $source -OutFile $destination

    $source = "https://slproweb.com/download/Win64OpenSSL-1_0_2u.exe"

    $destination = "C:\ovs-build-downloads\Win64OpenSSL-1_0_2u.exe"

    Invoke-WebRequest $source -OutFile $destination

    $source = "https://www.totalcommander.ch/win/tools/openssl-1.0.2u-x64_86-win64.zip"

    $destination = "C:\ovs-build-downloads\ssl\openssl-1.0.2u-x64_86-win64.zip"

    Invoke-WebRequest $source -OutFile $destination

    $source = "https://download.microsoft.com/download/3/2/2/3224B87F-CFA0-4E70-BDA3-3DE650EFEBA5/vcredist_x64.exe"

    $destination = "C:\openvswitch_compile\windows\ovs-windows-installer\redist\vcredist_x64.exe"

    Invoke-WebRequest $source -OutFile $destination

    7z x C:\ovs-build-downloads\ssl\openssl-1.0.2u-x64_86-win64.zip -oC:\ovs-build-downloads\ssl

    cd C:\pthreads-win32

    7z x C:\pthreads-win32\pthreads-win32.zip

    cd C:\ovs-build-downloads

    .\Win64OpenSSL-1_0_2u.exe /silent /verysilent /sp- /suppressmsgboxes

    Start-Sleep -s 30

    cd C:\openvswitch_compile

    python3 -m pip install pypiwin32 --disable-pip-version-check

build_script:
- '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"'
- C:\MinGW\msys\1.0\bin\bash -lc "echo \"C:/MinGW /mingw\" > /etc/fstab"
- C:\MinGW\msys\1.0\bin\bash -lc "cp /c/pthreads-win32/Pre-built.2/dll/x64/*.dll /c/openvswitch_compile/."
- C:\MinGW\msys\1.0\bin\bash -lc "mv /bin/link.exe /bin/link_copy.exe"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/openvswitch_compile && ./boot.sh"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/openvswitch_compile && ./configure CC=build-aux/cccl LD=\"`which link`\" LIBS=\"-lws2_32 -lShlwapi -liphlpapi -lwbemuuid -lole32 -loleaut32\" --prefix=C:/openvswitch/usr --localstatedir=C:/openvswitch/var --sysconfdir=C:/openvswitch/etc --with-pthread=C:/pthreads-win32/Pre-built.2 --enable-ssl --with-openssl=C:/OpenSSL-Win64 --with-vstudiotarget=\"%CONFIGURATION%\"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/openvswitch_compile && make"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/openvswitch_compile && make datapath_windows_analyze"
- cp C:\ovs-build-downloads\ssl\libeay32.dll C:\openvswitch_compile\windows\ovs-windows-installer\Services
- cp C:\ovs-build-downloads\ssl\libeay32.dll C:\openvswitch_compile\windows\ovs-windows-installer\Binaries
- cp C:\ovs-build-downloads\ssl\ssleay32.dll C:\openvswitch_compile\windows\ovs-windows-installer\Services
- cp C:\ovs-build-downloads\ssl\ssleay32.dll C:\openvswitch_compile\windows\ovs-windows-installer\Binaries
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/openvswitch_compile && make windows_installer"
- copy c:\openvswitch_compile\windows\ovs-windows-installer\bin\%CONFIGURATION%\OpenvSwitch.msi OpenvSwitch-%CONFIGURATION%.msi

artifacts:
  - path: OpenvSwitch-%CONFIGURATION%.msi
    name: openvswitch_installer
